### ISSUE TITLE
add `save` support for raw arrays

### ISSUE THREAD

**Issue by ssfrr** [JuliaAudio/LibSndFile.jl#13]
Currently the `save` method only dispatches when the data in a `SampleBuf`. We should also support raw Arrays.

**Comment by EMCP** [comment]
Wouldn't you just write the Array out into a file using the standard library?

**Comment by ssfrr** [comment]
This issue is for writing the raw arrays out to an audio file like a `.wav`, `.flac`, etc. writing the raw array to disk wouldn't have the proper headers and encoding.

**Comment by EMCP** [comment]
I guess I'm ignorant to the difference, since to me raw arrays would not longer be a `.wav` or a `.flac` .. but a collection of arrays that could be run through any conversion procedure into the needed end file type

**Comment by ssfrr** [comment]
ah, I see the confusion. I mean taking a raw array as input and outputting a `.wav` or `.flac` file, as opposed to the current behavior that expects the array to be wrapped in a `SampleBuf` first (which is basically a samplerate-aware wrapper around an array). It's actually possible that more recent work in SampledSignals.jl already handles that conversion, but I haven't checked recently.

In general

**Comment by ssfrr** [comment]
To clarify further, currently we support `save(buf::SampleBuf, "filename.wav", ...)` and we should also support `save(buf::Array, "filename.wav", ...)` (if that doesn't work already. if it works then I can close this issue) :)

**Comment by EMCP** [comment]
Looks like I just started coming around to this issue..

I will begin searching `SampledSignals.jl` for ways to save the `SampleBuf` to disk

```
## using regular write method
...
write(audio_sample_out, audio_sample)

```
Output
```
~/Dev/audio_pool/wav/Ambient Shaker-80bpm.wav 529200 44100.0
MethodError: no method matching write(::IOStream, ::FixedPointNumbers.Fixed{Int32,31})
Closest candidates are:
  write(::IO, ::Any) at io.jl:284
  write(::IO, ::Any...) at io.jl:286
  write(::IOStream, ::Char) at iostream.jl:214
  ...

Stacktrace:
 [1] write(::IOStream, ::SampledSignals.SampleBuf{FixedPointNumbers.Fixed{Int32,31},2}) at ./io.jl:307
 [2] save_sample(::Tuple{String,SampledSignals.SampleBuf{FixedPointNumbers.Fixed{Int32,31},2},Float64,Int64}, ::IOStream, ::IOStream) at ./In[26]:16
 [3] include_string(::String, ::String) at ./loading.jl:522
```

**Comment by ssfrr** [comment]
Can you post a minimal example of what you're trying to do? That'll make it easier to see where things are going wrong.

Generally you won't be using `write`, as that's for writing raw unformatted data to a stream. you'll want to use `save` to save data in a particular format, e.g. `save(somebuf, "somefile.wav")`

**Comment by EMCP** [comment]
I cracked it.. basically I am super new to Julia and editing in Notebooks.. I was attempting to save the entire SampleBuf .. along with it's `.samplerate` field.  All I really wanted was the `.data` field, and I successfully wrote it to disk once I pulled that out.

**Comment by ssfrr** [comment]
generally any time you have to reach into the `.data` field it is a bug in the library code. You should be able to save the `SampleBuf` object and the library should do the right thing.

One thing to be aware of is there's another Julia library called [`WAV.jl`](https://github.com/dancasimiro/WAV.jl) that can also be used to work with wav files. It doesn't currently integrate as tightly with the `SampledSignals` infrastructure, but has some other features (like supporting appending wav files) that haven't made it into my libraries yet.

**Comment by EMCP** [comment]
Thanks I will take a look at `Wav.jl` then.. most of the samples I pulled in are .wav but eventually will also need to grab the MP3 package.

**Comment by ssfrr** [comment]
This issue was fixed a while ago - LibSndFile now supports a `save` method for regular `Array`s, not just `SampleBuf`s.
