### ISSUE TITLE
sample rate?

### ISSUE THREAD

**Issue by EMCP** [JuliaAudio/LibSndFile.jl#14]
I'm looking around for options to sample wav files in JuliaLang.. 

I successfully loaded some .wav files, but then realized I hadn't given a sample rate, nor see any mention of one in the source.  Is there a lower level api call that I need to be looking at?

**Comment by ssfrr** [comment]
If you load an audio using `LibSndFile` you get a `SampleBuf` object, which knows its own samplerate (the samplerate, channel count, and sample type (e.g. float32) will match the file. If you want to resample to a different samplerate you can use `resample` from the `DSP` package. If you want to see the samplerate for a given buffer you can use `samplerate(buf)`, which comes from the `SampledSignals` package.

In general `SampledSignals` provides most of the API you'll use to work with audio buffers and streams. `LibSndFile`'s job is to take those buffers and streams and read/write files on disk.

**Comment by EMCP** [comment]
my call seems to be just getting back the raw array, is that because of the way I am calling `load(...)` ? 

```
function load_sample(filename)
    audio_sample = load(filename)
    duration = length(audio_sample)
    
    if(duration == 0)
        return nothing
    end
    
    if(duration > 5000000)
        return nothing
    end
    
    print(duration)   
    
    return (filename, audio_sample, duration)
end
```

**Comment by ssfrr** [comment]
Looks like you're data is fixed-point (encoded as integers), which is pretty common in wav files. You can convert to floats with `floatbuf = Float64.(buf)` (which is equivalent to calling `Float64(samp)` on each sample). `Float32` would work as well.

Can you put in a minimal working example (MWE) of the code you're running (that includes any `using...` statements) that's not giving you the output you expect?

**Comment by EMCP** [comment]
Sure, my entire thing is at 

https://github.com/EMCP/AudioNotebooks_Julia

The samples are not in this project (that would be GBs upon GBs)

**Comment by ssfrr** [comment]
you should be able to do:

```julia
using LibSndFile: load
using SampledSignals: samplerate

buf = load("path/to/file")
sr = samplerate(buf)
```

If that's still not doing what you expect would you mind posting a smaller self-contained block of code? The sort of thing I can easily paste into the REPL to see what's going on.

**Comment by EMCP** [comment]
This worked great! 

So if I want to resample, I should dig into that `SampledSignals` library I take it.  

Thank you

**Comment by ssfrr** [comment]
`resample` is actually part of the DSP library, because it's not audio specific.

There might be some rough edges with interfacing some of the DSP functions, some of which were originally written expecting `Array` types, rather than `AbstractArray` types (which would include `SampleBuf`). Don't hesitate to report issues.
