### ISSUE TITLE
trouble using the package

### ISSUE THREAD

**Issue by felluksch** [JuliaAudio/LibSndFile.jl#18]
Hi, 
I'm having trouble using this package. When trying to run the following lines of code in Jupyter Notebook, I get a warning and an error:
> WARNING: ignoring conflicting import of FileIO.load into Main
> MethodError: no method matching load(::String)

```
using FileIO: load, save, loadstreaming, savestreaming
import LibSndFile
using SampledSignals

buf = load("../path/to/file.wav")
```
```
using Pkg
println(isfile("../path/to/file.wav")) ### returns true
println(pkgs["FileIO"]) ### returns 1.0.7
println(pkgs["LibSndFile"]) ### returns 2.0.0
println(pkgs["SampledSignals"]) ### 2.0.0
```
This is basically copy-pasted from the readme, so I'm not quite sure why it isn't working.
Later, I simply want to calculate the total duration of a couple of wav files and thought I could achive this by iterating over the files (once I have loaded them), doing `nframes(buf)/samplerate(buf)` for each file and then adding up. So if there's a simpler solution, I'd be equally thankful if you could tell me. 
Thanks!

**Comment by ssfrr** [comment]
It looks like you've defined the symbol `load` somewhere else within your session (maybe in some previous experimentation). What do you see when you run `methods(load)`? Do you have the same issue if you start from a fresh session?

**Comment by ssfrr** [comment]
And for your second question: yes, `nframes(buf)/samplerate(buf)` seems like the way to go.

**Comment by felluksch** [comment]
Ah, thanks @ssfrr, just restarting worked (I have no idea what happened). 
Sorry to bother you again but 
`println(nframes(buf))` gives 
> MethodError: no method matching nframes(::Tuple{Array{Float64,2},Float32,UInt16,Array{WAV.WAVChunk,1}}). 

But judging from the Beat Slicing example and [this thread](https://github.com/JuliaAudio/LibSndFile.jl/issues/14) I should be able to just `load()` a file and then do stuff, right?

**Comment by ssfrr** [comment]
It looks like your file is being loaded by WAV.jl, not LibSndFile.jl. WAV returns a tuple of the raw audio data and the sample rate.

If WAV and LibSndFile are both installed, FileIO prefers WAV. If you remove the WAV package it should work as expected.

**Comment by felluksch** [comment]
Great, thanks a lot!
