### ISSUE TITLE
Compat module problem

### ISSUE THREAD

**Issue by Ronneesley** [JuliaAudio/LibSndFile.jl#27]
I'm using julia's version 1.3. When I run the code to build:

```julia
(v1.3) pkg> build LibSndFile
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/ne2iw/deps/build.log`
  Building Conda ───────────→ `~/.julia/packages/Conda/kLXeC/deps/build.log`
  Building FFTW ────────────→ `~/.julia/packages/FFTW/2okGQ/deps/build.log`
  Building LibCURL ─────────→ `~/.julia/packages/LibCURL/lWJxD/deps/build.log`
  Building WinRPM ──────────→ `~/.julia/packages/WinRPM/Y9QdZ/deps/build.log`
  Building Homebrew ────────→ `~/.julia/packages/Homebrew/s09IX/deps/build.log`
  Building LibSndFile ──────→ `~/.julia/packages/LibSndFile/2R0fx/deps/build.log`
┌ Error: Error building `LibSndFile`: 
│ ERROR: LoadError: ArgumentError: Package Compat not found in current path:
│ - Run `import Pkg; Pkg.add("Compat")` to install the Compat package.
│ 
│ Stacktrace:
│  [1] require(::Module, ::Symbol) at ./loading.jl:887
│  [2] include at ./boot.jl:328 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1105
│  [4] include(::Module, ::String) at ./Base.jl:31
│  [5] include(::String) at ./client.jl:424
│  [6] top-level scope at none:5
│ in expression starting at /home/ronneesley/.julia/packages/LibSndFile/2R0fx/deps/build.jl:2
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/backwards_compatible_isolation.jl:649
```

**Comment by ssfrr** [comment]
Can you update your packages and try again? It looks like you're running an older version of LibSndFile, and this issue should be fixed in v2.2.0.

**Comment by Ronneesley** [comment]
Yes. I'll try now.

**Comment by Ronneesley** [comment]
I'm running on 2.0.0 as you can see:

```julia
julia> pkgs = Pkg.installed();

julia> pkgs["LibSndFile"]
v"2.0.0"
```

I installed some minutes ago. When I updated it stayed on 2.0.0.

**Comment by Ronneesley** [comment]
When I installed by URL, I got this error message:

```julia
(v1.3) pkg> add https://github.com/JuliaAudio/LibSndFile.jl
  Updating git-repo `https://github.com/JuliaAudio/LibSndFile.jl`
  Updating git-repo `https://github.com/JuliaAudio/LibSndFile.jl`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package FFTW [7a1cc6ca]:
 FFTW [7a1cc6ca] log:
 ├─possible versions are: [0.1.0-0.1.2, 0.2.0-0.2.4, 0.3.0, 1.0.0-1.0.1, 1.1.0] or uninstalled
 ├─restricted to versions 1.0.1 by an explicit requirement, leaving only versions 1.0.1
 └─restricted by compatibility requirements with SampledSignals [bd7594eb] to versions: 1.1.0 — no versions left
   └─SampledSignals [bd7594eb] log:
     ├─possible versions are: [2.0.0, 2.1.0] or uninstalled
     └─restricted to versions 2.1.0-2 by LibSndFile [b13ce0c6], leaving only versions 2.1.0
       └─LibSndFile [b13ce0c6] log:
         ├─possible versions are: 2.2.0 or uninstalled
         └─LibSndFile [b13ce0c6] is fixed to version 2.2.0
```

Since after ```add FFTW```

**Comment by Ronneesley** [comment]
It's weird. The FFTW is in v1.0.1

```julia
julia> pkgs = Pkg.installed();

julia> pkgs["FFTW"]
v"1.0.1"
```
The same is happening with LibSndFile. At Github it's on v2.2.0 at Project.toml, but when I install, Julia installs v2.0.0.

At Github FFTW is on 1.1.0, but when I install, Julia installs version 1.0.1.

Both have releases on these versions v.2.2.0 (LibSndFile) and v1.1.0 (FFTW).
Where Julia search the last version of a module?

**Comment by Ronneesley** [comment]
After adding manually all these repositories:

https://github.com/JuliaGPU/GPUArrays.jl
https://github.com/JuliaMath/AbstractFFTs.jl
https://github.com/JuliaMath/FFTW.jl
https://github.com/JuliaAudio/LibSndFile.jl

Worked.

**Comment by ssfrr** [comment]
Hmm, that shouldn't be necessary. It seems like something is holding FFTW back to an older version. The "restricted to versions 1.0.1 by an explicit requirement, leaving only versions 1.0.1" makes me think that maybe at some point you did something that pinned FFTW to that specific version. Maybe try `free FFTW`, or `rm FFTW` followed by `add FFTW`?

**Comment by ssfrr** [comment]
To add some more context - it seems that for some reason Julia is convinced that it must use FFTW version 1.0.1, and because the latest version of LibSndFile is not compatible with that version, it won't install the latest version of LibSndFile. I guess I could relax the constraint on FFTW within LibSndFile, but I believe those older versions of FFTW have other compat-related issues, so you really want to get it updated to the latest.

**Comment by Ronneesley** [comment]
After the commands:

```julia
julia> using Pkg

julia> pkgs = Pkg.installed();

julia> pkgs["FFTW"]
v"1.0.1"

(v1.3) pkg> free FFTW
 Resolving package versions...
  Updating `~/.julia/environments/v1.3/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.3/Manifest.toml`
 [no changes]

(v1.3) pkg> rm FFTW
  Updating `~/.julia/environments/v1.3/Project.toml`
  [7a1cc6ca] - FFTW v1.0.1
  Updating `~/.julia/environments/v1.3/Manifest.toml`
 [no changes]

(v1.3) pkg> add FFTW
 Resolving package versions...
  Updating `~/.julia/environments/v1.3/Project.toml`
  [7a1cc6ca] + FFTW v1.0.1
  Updating `~/.julia/environments/v1.3/Manifest.toml`
 [no changes]

julia> pkgs = Pkg.installed();

julia> pkgs["FFTW"]
v"1.0.1"
```

The FFTW installed version is v1.0.1

**Comment by ssfrr** [comment]
Can you post the result of `pkg> status`? (use `]` to get to the `pkg>` prompt). Alternatively, you could try in a clean environment.

**Comment by ssfrr** [comment]
(actually might be better to move to discourse for this sort of support thing) see my post [here](https://discourse.julialang.org/t/how-to-play-an-audio-in-julia/31881/2)
