### ISSUE TITLE
readme documentation bug 

### ISSUE THREAD

**Issue by yurivish** [JuliaAudio/LibSndFile.jl#29]
This might not want to use `s` as the name of the stream — since it prevents the use of `s` as second.

Load a long file as a stream and plot the left channel from 2s to 3s
```
s = loadstream("myfile.ogg")
x = read(s, 4s)[2s..3s, 1]
close(s)
plot(domain(x), x)
```

**Comment by ssfrr** [comment]
fixed in #28 / #31
