### ISSUE TITLE
Can not installed LibSndFile package

### ISSUE THREAD

**Issue by nuclear718** [JuliaAudio/LibSndFile.jl#34]
Input:

`>Pkg.add("LibSndFile")`

return the error message:

`Resolving package versions...
Unsatisfiable requirements detected for package FixedPointNumbers [53c48c17]:
 FixedPointNumbers [53c48c17] log:
 ├─possible versions are: [0.5.0-0.5.3, 0.6.0-0.6.1, 0.7.0-0.7.1, 0.8.0-0.8.4] or uninstalled
 ├─restricted by compatibility requirements with MLDatasets [eb30cadb] to versions: [0.5.0-0.5.3, 0.6.0-0.6.1, 0.7.0-0.7.1, 0.8.0-0.8.4]
 │ └─MLDatasets [eb30cadb] log:......................`

===================================
**BackGround Info:**
_Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 5 3600X 6-Core Processor             
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver2)
Environment:
  JULIA.EXECUTABLEPATH = C:\Users\USER\AppData\Local\Julia-1.3.1\bin\ & set JULIA_NUM_THREADS=12 & julia.exe
  JULIA_NUM_THREADS = 12_

**Comment by ma-laforge** [comment]
FYI: Your issue is likely caused by `SampledSignals.jl` requiring an old version of `FixedPointNumbers`
-->https://github.com/JuliaAudio/SampledSignals.jl/issues/64#issuecomment-830925450
