### ISSUE TITLE
Play generated array

### ISSUE THREAD

**Issue by schneiderfelipe** [JuliaAudio/LibSndFile.jl#36]
Hi, does LibSndFile have a function equivalent to MATLAB's [`soundsc(y, Fs, nBits)`](https://www.mathworks.com/help/matlab/ref/soundsc.html)? How can I generate a simple sine wave and play it/save it as a WAV file? I'm struggling with a straightforward task, but I can't find how to do it anywhere.

**Comment by ssfrr** [comment]
no, libsndfile just reads and writes soundfiles on disk.

Check out WAV.jl which can handle both wav files and streams, or you can also use PortAudio.jl to record and playback audio. It's not currently registered, but it looks like there's some momentum brewing so hopefully it will be soon.
