### ISSUE TITLE
why does savestreaming FLAC only support PCM16Sample?

### ISSUE THREAD

**Issue by cdevane** [JuliaAudio/LibSndFile.jl#55]
Where is the limitation preventing FLAC from supporting other bit depths?   

from loadsave.jl

    if T == format"FLAC" && elemtype != PCM16Sample
        error("LibSndFile.jl: FLAC only supports 16-bit integer samples")
    end

**Comment by ssfrr** [comment]
When you call `save`, LibSndFile tries to match the destination file to the element type of the given array. FLAC supports 8bit, 16bit, and 24bit samples. Julia doesn't have a 24-bit integer type, only 32-bit.

The idea is that LibSndFile shouldn't be removing precision without you knowing about it, but honestly I think that LibSndFile is too strict here, and it's more hassle than it's worth.

I'd support a PR to make this a bit more lenient and auto-convert anything that's not exactly representable into 24-bit.

**Comment by cdevane** [comment]
Thanks Spencer.
